// Script de seed — popula o Firestore com os dados da planilha
// Rodar UMA vez: node src/seed.js (requer GOOGLE_APPLICATION_CREDENTIALS ou firebase login)
// OU via: npx -y firebase-tools@latest exec --project mh-agenda-campanha-2026 "node src/seed.js"

import { db } from './firebase.js';
import { collection, doc, setDoc, writeBatch } from 'firebase/firestore';

const ACOES = [
  {
    id: 'acao-001',
    descricao: 'Caminhada + panfletagem na Feira do Bairro Centro',
    local: 'Pinheiros',
    tipo: 'Território',
    categorias: ['Encontro com lideranças', 'Roda de conversa', 'Entrevista/Podcast', 'Visita a locais'],
    sugerido_por: 'João',
    envolvidos: 'João + Nay',
    status: 'Sugerida',
    data: '2026-08-15',
    estimativa: '20 pessoas',
    observacoes: 'Confirmar autorização da prefeitura para som',
    avaliacao: null,
  },
  {
    id: 'acao-002',
    descricao: 'Roda de conversa - Insper',
    local: 'Comitê',
    tipo: 'Relacionamento',
    categorias: ['Roda de conversa'],
    sugerido_por: 'Pedro Montes',
    envolvidos: null,
    status: 'Realizada',
    data: null,
    estimativa: '14 pessoas',
    observacoes: null,
    avaliacao: null,
  },
  {
    id: 'acao-003',
    descricao: 'Jantar grupo Sementes',
    local: 'Pinheiros',
    tipo: 'Relacionamento',
    categorias: ['Roda de conversa'],
    sugerido_por: 'Mab',
    envolvidos: null,
    status: 'Realizada',
    data: '2026-05-30',
    estimativa: '18 pessoas',
    observacoes: null,
    avaliacao: 'Muito positiva — engajou muitas mulheres e mães, saíram de lá envolvidas. Saiu +1 roda de conversa.',
  },
  {
    id: 'acao-004',
    descricao: 'Seminário de Mulheres c/ Marina Silva',
    local: 'PUC',
    tipo: 'Participação em Eventos',
    categorias: ['Evento com fala'],
    sugerido_por: null,
    envolvidos: null,
    status: 'Realizada',
    data: null,
    estimativa: null,
    observacoes: null,
    avaliacao: null,
  },
  {
    id: 'acao-005',
    descricao: 'Inauguração IF + ame animal',
    local: 'Mauá',
    tipo: 'Território',
    categorias: ['Visita a locais'],
    sugerido_por: null,
    envolvidos: null,
    status: 'Realizada',
    data: null,
    estimativa: null,
    observacoes: null,
    avaliacao: null,
  },
  {
    id: 'acao-006',
    descricao: 'Jantar Gabi',
    local: 'Pinheiros',
    tipo: 'Relacionamento',
    categorias: ['Roda de conversa'],
    sugerido_por: 'Mab',
    envolvidos: null,
    status: 'Realizada',
    data: '2026-07-06',
    estimativa: '16 pessoas',
    observacoes: null,
    avaliacao: null,
  },
  {
    id: 'acao-007',
    descricao: 'Movimento de Apoio candidaturas femininas PSB',
    local: 'Brasília',
    tipo: 'Participação em Eventos',
    categorias: ['Evento institucional'],
    sugerido_por: 'PSB',
    envolvidos: null,
    status: 'Em Construção',
    data: '2026-08-14',
    estimativa: null,
    observacoes: null,
    avaliacao: null,
  },
  {
    id: 'acao-008',
    descricao: 'Celebração ao Cooperativismo',
    local: 'Bela Vista',
    tipo: 'Participação em Eventos',
    categorias: ['Evento com fala'],
    sugerido_por: null,
    envolvidos: null,
    status: 'Em Construção',
    data: null,
    estimativa: null,
    observacoes: null,
    avaliacao: null,
  },
  {
    id: 'acao-009',
    descricao: 'Audiência pública — fechamento de salas do ensino estadual',
    local: 'Limeira',
    tipo: 'Participação em Eventos',
    categorias: ['Evento institucional'],
    sugerido_por: null,
    envolvidos: null,
    status: 'Sugerida',
    data: '2026-07-15',
    estimativa: null,
    observacoes: null,
    avaliacao: null,
  },
  {
    id: 'acao-010',
    descricao: 'Roda de Conversa com Marina Silva',
    local: 'Liberdade',
    tipo: 'Relacionamento',
    categorias: ['Roda de conversa'],
    sugerido_por: null,
    envolvidos: null,
    status: 'Sugerida',
    data: null,
    estimativa: null,
    observacoes: null,
    avaliacao: null,
  },
  {
    id: 'acao-011',
    descricao: '[JANTAR] Marina Silva, Marina Helou e LACLIMA',
    local: null,
    tipo: 'Relacionamento',
    categorias: ['Roda de conversa'],
    sugerido_por: null,
    envolvidos: null,
    status: 'Em Construção',
    data: null,
    estimativa: null,
    observacoes: null,
    avaliacao: null,
  },
  {
    id: 'acao-012',
    descricao: 'ALMOÇO com a artista Molly Gochman',
    local: null,
    tipo: 'Relacionamento',
    categorias: ['Conversa 1:1'],
    sugerido_por: null,
    envolvidos: null,
    status: 'Sugerida',
    data: '2026-07-21',
    estimativa: null,
    observacoes: null,
    avaliacao: null,
  },
  {
    id: 'acao-013',
    descricao: 'Aula de Democracia, Informação e Poder',
    local: null,
    tipo: 'Participação em Eventos',
    categorias: ['Evento institucional'],
    sugerido_por: null,
    envolvidos: null,
    status: 'Sugerida',
    data: null,
    estimativa: null,
    observacoes: null,
    avaliacao: null,
  },
];

export async function seedFirestore() {
  const batch = writeBatch(db);
  const col = collection(db, 'acoes');
  for (const acao of ACOES) {
    const ref = doc(col, acao.id);
    const { id, ...data } = acao;
    batch.set(ref, data);
  }
  await batch.commit();
  console.log(`✅ ${ACOES.length} ações enviadas ao Firestore com sucesso!`);
}

export { ACOES };
